version: "3.7"

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    expose:
    - 8086
    networks:
      influxdb:
        aliases:
          - influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: ruuvi
      DOCKER_INFLUXDB_INIT_BUCKET: ruuvi
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2:rw

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    networks:
      grafana:
        aliases:
         - grafana
      influxdb:
    volumes:
      - grafana-storage:/var/lib/grafana:rw

  mosquitto:
    image: eclipse-mosquitto:2.0-openssl
    container_name: mosquitto
    expose:
      - 1883 # MQTT no-tls port for RuuviBridge
    networks:
      mqtt:
        aliases:
          - mosquitto
    ports:
      - "8886:8886"  # MQTT Websocket open to world for Ruuvi Gateway
    volumes:
      - ./mosquitto/passwd:/mosquitto/passwd:rw
      - ./mosquitto/config:/mosquitto/config:rw
    restart: unless-stopped

  ruuvibridge:
    image: ghcr.io/scrin/ruuvibridge
    container_name: ruuvibridge
    restart: unless-stopped
    volumes:
      - ./ruuvibridge/config.yml:/config.yml:ro
    networks:
      mqtt:
      influxdb:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 is UDP
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data/caddy
      - ./caddy/config:/config/caddy
    networks:
      - mqtt
      - grafana

networks:
  mqtt:
  influxdb:
  grafana:

secrets:
  influxdb2-admin-username:
    file: ~/.config/influxdb2/admin-username
  influxdb2-admin-password:
    file: ~/.config/influxdb2/admin-password
  influxdb2-admin-token:
    file: ~/.config/influxdb2/admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage: