version: "3.7"

services:
  influxdb2:
    image: influxdb:2
    expose:
    - 8086
    ports:
      - 127.0.0.1:8086:8086
    networks:
      influxdb:
        aliases:
          - influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: ruuvi
      DOCKER_INFLUXDB_INIT_BUCKET: ruuvi
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2:rw

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      grafana:
        aliases:
         - grafana
      influxdb:
    volumes:
      - grafana-storage:/var/lib/grafana:rw

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    expose:
      - 1883
    networks:
      mqtt:
        aliases:
          - mosquitto
    ports:
      - "127.0.0.1:1883:1883" #default mqtt port
      - "127.0.0.1:9001:9001" #default mqtt port for websockets
    volumes:
      - ./mosquitto:/etc/mosquitto:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  ruuvibridge:
    image: ghcr.io/scrin/ruuvibridge
    container_name: ruuvibridge
    restart: unless-stopped
    # http listener (8080) and Prometheus (8081)
    expose:
    - 8080
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    volumes:
      - ./ruuvibridge/config.yml:/config.yml:ro
    networks:
      mqtt:
      influxdb:
      bridge:
        aliases:
        - ruuvibridge

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - mqtt
      - grafana
      - ruuvibridge

networks:
  mqtt:
  influxdb:
  grafana:

secrets:
  influxdb2-admin-username:
    file: ~/.config/influxdb2/admin-username
  influxdb2-admin-password:
    file: ~/.config/influxdb2/admin-password
  influxdb2-admin-token:
    file: ~/.config/influxdb2/admin-token

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage: